import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation/Navigation";

const inter = Inter({ subsets: ["latin"] });

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto_mono.variable}`}>
        <header>
          <Navigation />
          <Navigation isLogoNav={true} hasNavItems={true} hasProfile={true} />
        </header>
        {children}
      </body>
    </html>
  );
}
